# Generated by Django 3.2.5 on 2022-10-21 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('WebDev', 'WebDev'), ('AppDev', 'AppDev'), ('ML', 'ML'), ('Others', 'Others')], default='others', max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'easy'), ('medium', 'medium'), ('tough', 'tough')], default='medium', max_length=10),
        ),
    ]
